# Generated by Django 3.1.5 on 2021-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pfp',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
