# Generated by Django 3.1.5 on 2021-01-20 21:48

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210119_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=99, size=[128, 128], upload_to='djangosite/static/img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(max_length=100000),
        ),
    ]
