# Generated by Django 3.1.5 on 2021-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rolepermissions_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
