# Generated by Django 3.1.5 on 2021-01-22 00:03

from django.db import migrations, models
import forums.models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='perms',
            field=models.CharField(default='None', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(null=True, on_delete=forums.models.Category, to='forums.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
