# Generated by Django 3.1.5 on 2021-01-25 23:21

from django.db import migrations, models
import forums.models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20210121_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('threads', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('latest_thread_time', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=forums.models.Forum, to='forums.forum')),
            ],
        ),
    ]
