# Generated by Django 3.1.5 on 2021-01-26 01:17

from django.db import migrations, models
import forums.models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20210125_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=forums.models.SubForum, to='forums.subforum'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=forums.models.Forum, to='forums.forum'),
        ),
    ]
