# Generated by Django 3.1.5 on 2021-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20210125_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='perms',
        ),
        migrations.AddField(
            model_name='forum',
            name='perms',
            field=models.ManyToManyField(to='forums.ForumPermission'),
        ),
        migrations.AddField(
            model_name='category',
            name='perms',
            field=models.ManyToManyField(to='forums.ForumPermission'),
        ),
    ]
