# Generated by Django 3.1.5 on 2021-02-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_delete_forumpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='perm',
            field=models.CharField(default='cate-<django.db.models.fields.CharField>', max_length=150),
        ),
        migrations.AddField(
            model_name='forum',
            name='perm',
            field=models.CharField(default='forum-<django.db.models.fields.CharField>', max_length=150),
        ),
        migrations.AddField(
            model_name='subforum',
            name='perm',
            field=models.CharField(default='subf-<django.db.models.fields.CharField>', max_length=150),
        ),
    ]
